
export default new Map([
["src/content/blog/astro-performance-guide.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fastro-performance-guide.mdx&astroContentModuleFlag=true")],
["src/content/blog/creative-image-layouts.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fcreative-image-layouts.mdx&astroContentModuleFlag=true")],
["src/content/blog/hello-world.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhello-world.mdx&astroContentModuleFlag=true")],
["src/content/updates/blog-platform-beta-launch.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fupdates%2Fblog-platform-beta-launch.mdx&astroContentModuleFlag=true")],
["src/content/updates/skyscan-architecture-design.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fupdates%2Fskyscan-architecture-design.mdx&astroContentModuleFlag=true")],
["src/content/updates/skyscan-aws-api-research.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fupdates%2Fskyscan-aws-api-research.mdx&astroContentModuleFlag=true")],
["src/content/updates/blog-platform-v2-release.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fupdates%2Fblog-platform-v2-release.mdx&astroContentModuleFlag=true")],
["src/content/updates/skyscan-beta-testing.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fupdates%2Fskyscan-beta-testing.mdx&astroContentModuleFlag=true")],
["src/content/updates/skyscan-competitive-analysis.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fupdates%2Fskyscan-competitive-analysis.mdx&astroContentModuleFlag=true")],
["src/content/updates/skyscan-cli-interface.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fupdates%2Fskyscan-cli-interface.mdx&astroContentModuleFlag=true")],
["src/content/updates/skyscan-aws-provider.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fupdates%2Fskyscan-aws-provider.mdx&astroContentModuleFlag=true")],
["src/content/updates/skyscan-core-engine.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fupdates%2Fskyscan-core-engine.mdx&astroContentModuleFlag=true")],
["src/content/updates/skyscan-edge-insight.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fupdates%2Fskyscan-edge-insight.mdx&astroContentModuleFlag=true")],
["src/content/updates/skyscan-prototype-complete.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fupdates%2Fskyscan-prototype-complete.mdx&astroContentModuleFlag=true")],
["src/content/updates/skyscan-initial-idea.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fupdates%2Fskyscan-initial-idea.mdx&astroContentModuleFlag=true")],
["src/content/updates/skyscan-plugin-architecture.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fupdates%2Fskyscan-plugin-architecture.mdx&astroContentModuleFlag=true")],
["src/content/updates/skyscan-security-rules-research.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fupdates%2Fskyscan-security-rules-research.mdx&astroContentModuleFlag=true")],
["src/content/updates/skyscan-v1-launch.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fupdates%2Fskyscan-v1-launch.mdx&astroContentModuleFlag=true")],
["src/content/updates/skyscan-wasm-feasibility.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fupdates%2Fskyscan-wasm-feasibility.mdx&astroContentModuleFlag=true")],
["src/content/updates/skyscan-wasm-compilation.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fupdates%2Fskyscan-wasm-compilation.mdx&astroContentModuleFlag=true")]]);
		